// ─────────────────────────────────────────────────────────────────────────────
// gimi_arm64 — Android Launcher: Mod Manager Service Implementation
// ─────────────────────────────────────────────────────────────────────────────

#include "launcher/mod_manager_service.h"
#include "utils/logger.h"
#include <fstream>
#include <iostream>

namespace gimi {

ModManagerService& ModManagerService::instance() noexcept {
    static ModManagerService s_service;
    return s_service;
}

std::vector<ModItem> ModManagerService::scan_mods(const std::string& mods_root) noexcept {
    m_mods.clear();
    std::error_code ec;

    if (!std::filesystem::exists(mods_root, ec)) {
        LOGE("ModManagerService: Mods directory does not exist: %s", mods_root.c_str());
        return m_mods;
    }

    for (const auto& entry : std::filesystem::directory_iterator(mods_root, ec)) {
        if (entry.is_directory()) {
            std::string folder_name = entry.path().filename().string();
            bool is_disabled = (folder_name.rfind(".disabled") != std::string::npos);
            
            ModItem item{};
            item.name = is_disabled ? folder_name.substr(0, folder_name.length() - 9) : folder_name;
            item.path = entry.path().string();
            item.enabled = !is_disabled;
            item.author = "Unknown";
            item.resource_count = 0;

            // Count .ini files inside mod directory
            for (const auto& file : std::filesystem::directory_iterator(entry.path(), ec)) {
                if (file.path().extension() == ".ini") {
                    item.resource_count++;
                }
            }

            m_mods.push_back(item);
            LOGI("ModManagerService: Found mod '%s' (Enabled: %d)", item.name.c_str(), item.enabled);
        }
    }

    return m_mods;
}

bool ModManagerService::set_mod_enabled(const std::string& mod_path, bool enable) noexcept {
    std::error_code ec;
    std::filesystem::path p(mod_path);

    if (!std::filesystem::exists(p, ec)) return false;

    std::string current_name = p.filename().string();
    bool is_currently_disabled = (current_name.rfind(".disabled") != std::string::npos);

    if (enable && is_currently_disabled) {
        std::string new_name = current_name.substr(0, current_name.length() - 9);
        std::filesystem::path new_path = p.parent_path() / new_name;
        std::filesystem::rename(p, new_path, ec);
        return !ec;
    } else if (!enable && !is_currently_disabled) {
        std::string new_name = current_name + ".disabled";
        std::filesystem::path new_path = p.parent_path() / new_name;
        std::filesystem::rename(p, new_path, ec);
        return !ec;
    }

    return true;
}

std::string ModManagerService::generate_active_config() const noexcept {
    std::string config = "; Auto-generated by GIMI Launcher\n[Global]\n";
    for (const auto& mod : m_mods) {
        if (mod.enabled) {
            config += "ActiveMod = " + mod.name + "\n";
        }
    }
    return config;
}

} // namespace gimi
