# Gradle project-wide properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.overridePathCheck=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true

# Disable analytics and build services to avoid service isolation errors
android.analytics.writeToStatsd=false
org.gradle.vfs.watch=false
kotlin.build.report.enable=false
